// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, password, refresh_token, email, is_email_verified, is_active, created_at, updated_at FROM users
WHERE (id = $1 OR email = $2)
LIMIT 1
`

type GetUserParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithRefreshTokens = `-- name: GetUserWithRefreshTokens :one
SELECT u.id, u.first_name, u.last_name, u.password, u.refresh_token, u.email, u.is_email_verified, u.is_active, u.created_at, u.updated_at, rt.id, rt.user_id, rt.token_hash, rt.issued_at, rt.expires_at
FROM users u
LEFT JOIN refresh_tokens rt ON u.id = rt.user_id
WHERE u.id = $1
`

type GetUserWithRefreshTokensRow struct {
	ID              uuid.UUID          `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Password        string             `json:"password"`
	RefreshToken    pgtype.Text        `json:"refresh_token"`
	Email           string             `json:"email"`
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID_2            pgtype.UUID        `json:"id_2"`
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetUserWithRefreshTokens(ctx context.Context, id uuid.UUID) (GetUserWithRefreshTokensRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRefreshTokens, id)
	var i GetUserWithRefreshTokensRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  id, first_name, last_name, email, is_email_verified, is_active, password
) VALUES (
  uuid_generate_v4(), $1, $2, $3, $4, $5, $6
)
RETURNING id, first_name, last_name, password, refresh_token, email, is_email_verified, is_active, created_at, updated_at
`

type InsertUserParams struct {
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Email           string      `json:"email"`
	IsEmailVerified pgtype.Bool `json:"is_email_verified"`
	IsActive        pgtype.Bool `json:"is_active"`
	Password        string      `json:"password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.IsEmailVerified,
		arg.IsActive,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, password, refresh_token, email, is_email_verified, is_active, created_at, updated_at FROM users
WHERE ($1 IS NULL OR is_active = $1)
AND ($2 IS NULL OR is_email_verified = $2)
ORDER BY first_name
`

type ListUsersParams struct {
	IsActive        interface{} `json:"is_active"`
	IsEmailVerified interface{} `json:"is_email_verified"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.IsActive, arg.IsEmailVerified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Password,
			&i.RefreshToken,
			&i.Email,
			&i.IsEmailVerified,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
  set first_name = $2,
  last_name = $3
WHERE id = $1
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.FirstName, arg.LastName)
	return err
}
