default:
  just --list

init:
  terraform init -upgrade

validate:
  terraform validate

format:
  terraform fmt

plan:
  @echo "Running terraform plan"
  terraform plan -out main.tfplan
  terraform show -no-color main.tfplan > tfplan.txt

apply: validate
  @echo "Applying terraform plan"
  terraform apply main.tfplan
