// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Collection struct {
	ID          int64
	Name        string
	Description sql.NullString
}

type Command struct {
	ID          int64
	Name        string
	Description sql.NullString
	Command     sql.NullString
}
