// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              int32
	FirstName       string
	LastName        string
	Password        string
	Email           string
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	GithubHandle    pgtype.Text
}
