// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Command struct {
	ID          int32
	UserID      int32
	Command     string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CommandTag struct {
	CommandID int32
	TagID     int32
}

type RefreshToken struct {
	ID        int32
	UserID    pgtype.Int8
	TokenHash string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Tag struct {
	ID          int32
	UserID      int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID              int32
	FirstName       string
	LastName        string
	Password        string
	RefreshToken    pgtype.Text
	Email           string
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
