FROM golang:1.22.5 AS build-stage

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /termflow-api ./cmd/api/main.go

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /termflow-api /termflow-api

EXPOSE 80
EXPOSE 443

USER nonroot:nonroot

ENTRYPOINT ["/termflow-api"]
